import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="w-full flex justify-center border-b border-gray-200 bg-white py-4 mb-8 sticky top-0 z-50">
          <ul className="flex gap-8 text-base font-medium text-gray-800">
            <li><Link href="/">Home</Link></li>
            <li><Link href="/featured-projects">Featured Projects</Link></li>
            <li><Link href="/research">Research</Link></li>
            <li><Link href="/industry">Industry</Link></li>
            <li><Link href="/coursework">Coursework</Link></li>
            <li><Link href="/activities">Activities</Link></li>
            <li><Link href="/debug">Debug</Link></li>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  );
}
